### PR TITLE
why not for vendor?

### PR DESCRIPTION
**Pull request by Subinsmani**

### CODE REVIEW

**Comment by Akianonymus** [comment]
this is just an example 😂, lol

**Comment by Akianonymus** [comment]
i forgot to push here this commit

https://github.com/Akianonymus/Firmware_Extraction/commit/52abfb959dcf8b56fb5d3190df5b22e91ac95a3d

**Comment by ghostrider-reborn** [comment]
lmaoborghini

**Comment by Akianonymus** [comment]
😠

**Pull request closed without merging**
